export default {
    NEWS_ADD: 'NEWS_ADD',

    SOURCES_ADD: 'SOURCES_ADD',

    SOURCES_LOAD_FEED_ERROR: 'SOURCES_LOAD_FEED_ERROR',
    SOURCES_LOAD_FEED_RECEIVED: 'SOURCES_LOAD_FEED_RECEIVED',
    SOURCES_LOAD_FEED_REQUEST: 'SOURCES_LOAD_FEED_REQUEST',

    SOURCES_UNKNOWN_SOURCE_TYPE: 'SOURCES_UNKNOWN_SOURCE_TYPE',
};
